---
all:
  children:
    controller:
      hosts:
        controller01:
          ansible_host: 192.168.1.101
          ansible_user: ubuntu
        controller02:
          ansible_host: 192.168.1.102
          ansible_user: ubuntu
        controller03:
          ansible_host: 192.168.1.103
          ansible_user: ubuntu
    compute:
      hosts:
        compute01:
          ansible_host: 192.168.1.104
          ansible_user: ubuntu
        compute02:
          ansible_host: 192.168.1.105
          ansible_user: ubuntu
        compute03:
          ansible_host: 192.168.1.106
          ansible_user: ubuntu
